image:
  repository: artifactory.dagility.com/docker/workflow-test-gitlab-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: workflow-test-gitlab-backend-default.dagility.com
    paths:
    - /
serviceAccount:
  create: false
